Use a dockerized Mastodon as target for the e2e tests #95
Try again with traefik instead of nginx. I'm more familiar with it and use it for my projects. So it is more like my prod setup.
Credentials are used only in this e2e setup so it should be ok to include them.

seism0saurus

                 #++#
               +--------+
              +------++++                 #
             +--#++++-                   +
            #---+#                       +
            +---+                        .-
            +--+                           #-
            +--+                             #--
       -    +---                               --  -
            +---+                               #-+
            .+---+                               #-+
             +----+                               --#
              +-------+++#.                       --#
     .        #---------------+++-                --#
              #+------------------++             #-+
              ++---------------------+          +-+#
               ++++--------------------+++++++---+
               -++++++-------+---+------------++
                ++++++++-----+++++---+##+###-
         .       ++#+++++----+###+---#
                  ++#####+----# ++---#
                  +-+#    #---#  ++-++
                  +-++   ##+--+   #++++
                 ++-+#    .+--+    ++++
                 +--+#    +---+    ---
                # -++ .   +---#
                          . -.-

diff --git a/e2e-infrastructure/docker-compose.yaml b/e2e-infrastructure/docker-compose.yaml
--- a/e2e-infrastructure/docker-compose.yaml
+++ b/e2e-infrastructure/docker-compose.yaml
@@ -1,7 +1,4 @@
-version: "3"
-
 networks:
-  web:
   mastodon:
 
 services:
@@ -10,6 +7,8 @@ services:
     container_name: db
     restart: always
     shm_size: 256mb
+    expose:
+      - "5432"
     networks:
       - mastodon
     healthcheck:
@@ -25,6 +24,8 @@ services:
     image: redis:7-alpine
     container_name: redis
     restart: always
+    expose:
+      - "6379"
     networks:
       - mastodon
     healthcheck:
@@ -38,10 +39,17 @@ services:
     restart: always
     env_file: mastodon.env
     command: bundle exec puma -C config/puma.rb
+    expose:
+      - "3000"
     networks:
       - mastodon
+    labels:
+      - "traefik.enable=true"
+      - "traefik.http.routers.mastodon.rule=Host(`proxy`) && !PathPrefix(`/api/v1/streaming`)"
+      - "traefik.http.routers.mastodon.entrypoints=websecure"
+      - "traefik.http.routers.mastodon.tls=true"
     healthcheck:
-      test: ['CMD-SHELL',"curl -s --noproxy localhost localhost:3000/health | grep -q 'OK' || exit 1"]
+      test: ['CMD-SHELL',"curl --noproxy localhost localhost:3000/health | grep -q 'OK' || exit 1"]
     volumes:
       - ./mastodon:/mastodon/public/system
     depends_on:
@@ -54,10 +62,17 @@ services:
     restart: always
     env_file: mastodon.env
     command: node ./streaming/index.js
+    expose:
+      - "4000"
+    labels:
+      - "traefik.enable=true"
+      - "traefik.http.routers.streaming.rule=Host(`proxy`) && PathPrefix(`/api/v1/streaming`)"
+      - "traefik.http.routers.streaming.entrypoints=websecure"
+      - "traefik.http.routers.streaming.tls=true"
     networks:
       - mastodon
     healthcheck:
-      test: ['CMD-SHELL', "curl -s --noproxy localhost localhost:4000/api/v1/streaming/health | grep -q 'OK' || exit 1"]
+      test: ['CMD-SHELL', "curl --noproxy localhost localhost:4000/api/v1/streaming/health | grep -q 'OK' || exit 1"]
     depends_on:
       - db
       - redis
@@ -78,43 +93,59 @@ services:
       - db
       - redis
 
-  nginx:
-    image: nginx:stable-alpine
-    container_name: nginx
+  proxy:
+    image: traefik:3
+    container_name: proxy
     restart: always
     ports:
       - "80:80"
       - "443:443"
+      - "8090:8080"
     volumes:
-      - ./nginx.conf:/etc/nginx/conf.d/default.conf
-      - ./nginx.crt:/etc/nginx/certs/nginx.crt
-      - ./nginx.key:/etc/nginx/certs/nginx.key
+      - ./traefik.yml:/traefik.yml
+      - ./dynamic.yml:/dynamic.yml
+      - ./proxy.crt:/etc/ssl/proxy.crt
+      - ./proxy.key:/etc/ssl/proxy.key
+      - /var/run/docker.sock:/var/run/docker.sock
     networks:
-      - web
       - mastodon
+    labels:
+      - "traefik.enable=true"
+      - "traefik.http.routers.dashboard.rule=Host(`dashboard.localhost`)"
+      - "traefik.http.routers.dashboard.entrypoints=websecure"
+      - "traefik.http.routers.dashboard.tls=true"
+      - "traefik.http.routers.dashboard.service=api@internal"
+    healthcheck:
+      test: ['CMD-SHELL', "traefik healthcheck"]
+      interval: 30s
+      timeout: 10s
+      retries: 5
     depends_on:
       - web
       - streaming
-    healthcheck:
-      test: ['CMD-SHELL', "curl -s localhost:80 | grep -q '301' || exit 1"]
 
   glacier:
     container_name: glacier
     image: ghcr.io/seism0saurus/glacier:${GLACIER_IMAGE_TAG}
+    build:
+      context: ./glacier
+      dockerfile: Dockerfile
+    restart: always
     ports:
       - "8080:8080"
     networks:
       - mastodon
     volumes:
-      - ./nginx.crt:/certificates/nginx.crt
+      # Mount the certificate of the proxy service so no TLS errors are thrown
+      - ./proxy.crt:/certificates/proxy.crt
     environment:
       # Start spring with the default profile
       SPRING_PROFILES_ACTIVE: "default"
 
-      # Access the
-      INSTANCE: "nginx"
-      HANDLE: "glacier_e2e_test"
-      ACCESS_KEY: "1Ukr3V1otQaiOyk-BcexmgQvO3EGzgccxeicWVnnAnE"
+      # Access the e2e mastodon instance. Key is only usable in this local instance, so it is not a problem to publish it.
+      INSTANCE: "proxy"
+      HANDLE: "glacier_e2e_test@proxy"
+      ACCESS_KEY: "hMfsEYl9Hgk2Pt-iTyZyvKvfbXh9tjXV41-tsr3vRak"
 
       # informational settings for gdpr page and others
       MY_DOMAIN: "localhost:443"
@@ -127,11 +158,62 @@ services:
       MY_MAIL: "kontakt@seism0saurus.de"
       MY_PHONE: "+1234567890"
 
-      USE_SYSTEM_CA_CERTS: 1
+      # Use the system certificates which got mounted with the volume
+      USE_SYSTEM_CA_CERTS: true
+      DEVMODE: true
     healthcheck:
-      test: ['CMD-SHELL', "curl -s localhost:8080 | grep -q 'OK' || exit 1"]
+      test: [ 'CMD-SHELL', "wget -q --spider localhost:8080 || exit 1" ]
     depends_on:
-      - nginx
+      - proxy
       - sidekiq
       - streaming
       - web
+
+  playwright:
+    container_name: playwright
+    image: mcr.microsoft.com/playwright:v1.50.1
+    networks:
+      - mastodon
+    volumes:
+      - ../:/repo
+    working_dir: /repo/frontend
+    command:
+      - /bin/bash
+      - -c
+      - |
+        count=0
+        max_retries=60
+        while ! curl -ksf https://proxy:443/.well-known/nodeinfo &> /dev/null; do
+          count=$((count + 1))
+          if [ "$${count}" -ge "$${max_retries}" ]; then
+            echo "Max retries reached ($${max_retries}). Aborting."
+            exit 1
+          fi
+          echo "Attempt $$count/$${max_retries}: Waiting for proxy to be ready..."
+          sleep 2
+        done
+        echo "proxy is ready!"
+
+        count=0
+        max_retries=60
+        while ! curl -ksf http://glacier:8080/ &> /dev/null; do
+          count=$((count + 1))
+          if [ "$${count}" -ge "$${max_retries}" ]; then
+            echo "Max retries reached ($${max_retries}). Aborting."
+            exit 1
+          fi
+          echo "Attempt $$count/$${max_retries}: Waiting for glacier to be ready..."
+          sleep 2
+        done
+
+        npx playwright test
+    environment:
+      MASTODON_USER_API_URL: "https://proxy"
+      GLACIER_HANDLE: "@glacier_e2e_test@proxy"
+      BASE_URL: "http://glacier:8080"
+      WAIT_FOR: "15000"
+    depends_on:
+      - proxy
+      - streaming
+      - web
+      - glacier
